//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelSDK
{
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendAdditionalAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuppressionListData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuppressionListContext))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuppressionListDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlatformApplicationPackage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlatformApplication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationInstances))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PublicationSubscriber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Publication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProgramManifestTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileTriggerTypeLastPull))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileTrigger))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReplyMailManagementConfiguration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegrationProfileDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegrationProfile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Layout))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Portfolio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceSpecification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Authentication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsernameAuthentication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PublicKeyManagement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectExtension))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataExtensionObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkSend))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListSend))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportResultsSummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportDefinitionFieldMap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSSharedKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseMOKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendEmailMOKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HelpMOKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleOptInMOKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsubscribeFromSMSPublicationMOKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendSMSMOKeyword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSMOEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSMTEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagingConfiguration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagingVendorKind))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSTriggeredSend))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VoiceTriggeredSend))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AsyncRequestResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TriggeredSendSummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberSendResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TriggeredSend))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendSummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Link))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Send))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListAttributeRestrictedValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListSubscriber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackingEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveredEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForwardedEmailOptInEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForwardedEmailEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SurveyEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotSentEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SentEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClickEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsubEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BounceEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Message))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BrandTag))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Brand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountPrivateLabel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtractTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtractDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtractDescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentValidation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataFolder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SsoIdentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LandingPage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationNotification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationActivityInstance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationTask))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationTaskInstance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScheduleDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileTransferLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackingUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataExtensionTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataExtensionField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataExtension))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AudienceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendDefinitionList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TriggeredSendExclusionList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GlobalUnsubscribeCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subscriber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(List))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Email))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrivateDomainSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Certificate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentArea))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrivateDomain))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrivateIP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryProfile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InteractionBaseObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InteractionDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Automation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutomationInstance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileTransferActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReportActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MobilePushSendMessageActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MobileConnectSendSmsActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MobileConnectRefreshListActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsSendActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageSendActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataExtractActivity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmailSendDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSTriggeredSendDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VoiceTriggeredSendDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TriggeredSendDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Campaign))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SenderProfile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendClassification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Permission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Role))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessRule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Account))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessUnit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeZone))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Locale))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserAccess))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exacttarget.com/wsdl/partnerAPI")]
    public partial class APIObject
    {
        
        private ClientID clientField;
        
        private string partnerKeyField;
        
        private APIProperty[] partnerPropertiesField;
        
        private System.DateTime createdDateField;
        
        private bool createdDateFieldSpecified;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private bool modifiedDateFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string objectIDField;
        
        private string customerKeyField;
        
        private Owner ownerField;
        
        private string correlationIDField;
        
        private string objectStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClientID Client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string PartnerKey
        {
            get
            {
                return this.partnerKeyField;
            }
            set
            {
                this.partnerKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PartnerProperties", Order=2)]
        public APIProperty[] PartnerProperties
        {
            get
            {
                return this.partnerPropertiesField;
            }
            set
            {
                this.partnerPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
                this.createdDateFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateSpecified
        {
            get
            {
                return this.createdDateFieldSpecified;
            }
            set
            {
                this.createdDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
                this.modifiedDateFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified
        {
            get
            {
                return this.modifiedDateFieldSpecified;
            }
            set
            {
                this.modifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.idFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ObjectID
        {
            get
            {
                return this.objectIDField;
            }
            set
            {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerKey
        {
            get
            {
                return this.customerKeyField;
            }
            set
            {
                this.customerKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Owner Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ObjectState
        {
            get
            {
                return this.objectStateField;
            }
            set
            {
                this.objectStateField = value;
            }
        }
    }
}
