namespace FuelSDK
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exacttarget.com/wsdl/partnerAPI")]
    public partial class ImportDefinition : InteractionDefinition
    {
        
        private bool allowErrorsField;
        
        private bool allowErrorsFieldSpecified;
        
        private APIObject destinationObjectField;
        
        private ImportDefinitionFieldMappingType fieldMappingTypeField;
        
        private bool fieldMappingTypeFieldSpecified;
        
        private FieldMap[] fieldMapsField;
        
        private string fileSpecField;
        
        private FileType fileTypeField;
        
        private bool fileTypeFieldSpecified;
        
        private AsyncResponse notificationField;
        
        private FileTransferLocation retrieveFileTransferLocationField;
        
        private ImportDefinitionSubscriberImportType subscriberImportTypeField;
        
        private bool subscriberImportTypeFieldSpecified;
        
        private ImportDefinitionUpdateType updateTypeField;
        
        private bool updateTypeFieldSpecified;
        
        private int maxFileAgeField;
        
        private bool maxFileAgeFieldSpecified;
        
        private int maxFileAgeScheduleOffsetField;
        
        private bool maxFileAgeScheduleOffsetFieldSpecified;
        
        private int maxImportFrequencyField;
        
        private bool maxImportFrequencyFieldSpecified;
        
        private string delimiterField;
        
        private int headerLinesField;
        
        private bool headerLinesFieldSpecified;
        
        private ImportDefinitionAutoGenerateDestination autoGenerateDestinationField;
        
        private string controlColumnField;
        
        private ImportDefinitionColumnBasedActionType controlColumnDefaultActionField;
        
        private bool controlColumnDefaultActionFieldSpecified;
        
        private ImportDefinitionColumnBasedAction[] controlColumnActionsField;
        
        private string endOfLineRepresentationField;
        
        private string nullRepresentationField;
        
        private bool standardQuotedStringsField;
        
        private bool standardQuotedStringsFieldSpecified;
        
        private string filterField;
        
        private Locale dateFormattingLocaleField;
        
        private bool deleteFileField;
        
        private bool deleteFileFieldSpecified;
        
        private APIObject sourceObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AllowErrors
        {
            get
            {
                return this.allowErrorsField;
            }
            set
            {
                this.allowErrorsField = value;
                this.allowErrorsFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowErrorsSpecified
        {
            get
            {
                return this.allowErrorsFieldSpecified;
            }
            set
            {
                this.allowErrorsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public APIObject DestinationObject
        {
            get
            {
                return this.destinationObjectField;
            }
            set
            {
                this.destinationObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ImportDefinitionFieldMappingType FieldMappingType
        {
            get
            {
                return this.fieldMappingTypeField;
            }
            set
            {
                this.fieldMappingTypeField = value;
                this.fieldMappingTypeFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FieldMappingTypeSpecified
        {
            get
            {
                return this.fieldMappingTypeFieldSpecified;
            }
            set
            {
                this.fieldMappingTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FieldMap[] FieldMaps
        {
            get
            {
                return this.fieldMapsField;
            }
            set
            {
                this.fieldMapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FileSpec
        {
            get
            {
                return this.fileSpecField;
            }
            set
            {
                this.fileSpecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public FileType FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
                this.fileTypeFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileTypeSpecified
        {
            get
            {
                return this.fileTypeFieldSpecified;
            }
            set
            {
                this.fileTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public AsyncResponse Notification
        {
            get
            {
                return this.notificationField;
            }
            set
            {
                this.notificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public FileTransferLocation RetrieveFileTransferLocation
        {
            get
            {
                return this.retrieveFileTransferLocationField;
            }
            set
            {
                this.retrieveFileTransferLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ImportDefinitionSubscriberImportType SubscriberImportType
        {
            get
            {
                return this.subscriberImportTypeField;
            }
            set
            {
                this.subscriberImportTypeField = value;
                this.subscriberImportTypeFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubscriberImportTypeSpecified
        {
            get
            {
                return this.subscriberImportTypeFieldSpecified;
            }
            set
            {
                this.subscriberImportTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ImportDefinitionUpdateType UpdateType
        {
            get
            {
                return this.updateTypeField;
            }
            set
            {
                this.updateTypeField = value;
                this.updateTypeFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateTypeSpecified
        {
            get
            {
                return this.updateTypeFieldSpecified;
            }
            set
            {
                this.updateTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int MaxFileAge
        {
            get
            {
                return this.maxFileAgeField;
            }
            set
            {
                this.maxFileAgeField = value;
                this.maxFileAgeFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxFileAgeSpecified
        {
            get
            {
                return this.maxFileAgeFieldSpecified;
            }
            set
            {
                this.maxFileAgeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int MaxFileAgeScheduleOffset
        {
            get
            {
                return this.maxFileAgeScheduleOffsetField;
            }
            set
            {
                this.maxFileAgeScheduleOffsetField = value;
                this.maxFileAgeScheduleOffsetFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxFileAgeScheduleOffsetSpecified
        {
            get
            {
                return this.maxFileAgeScheduleOffsetFieldSpecified;
            }
            set
            {
                this.maxFileAgeScheduleOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int MaxImportFrequency
        {
            get
            {
                return this.maxImportFrequencyField;
            }
            set
            {
                this.maxImportFrequencyField = value;
                this.maxImportFrequencyFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxImportFrequencySpecified
        {
            get
            {
                return this.maxImportFrequencyFieldSpecified;
            }
            set
            {
                this.maxImportFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Delimiter
        {
            get
            {
                return this.delimiterField;
            }
            set
            {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int HeaderLines
        {
            get
            {
                return this.headerLinesField;
            }
            set
            {
                this.headerLinesField = value;
                this.headerLinesFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderLinesSpecified
        {
            get
            {
                return this.headerLinesFieldSpecified;
            }
            set
            {
                this.headerLinesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public ImportDefinitionAutoGenerateDestination AutoGenerateDestination
        {
            get
            {
                return this.autoGenerateDestinationField;
            }
            set
            {
                this.autoGenerateDestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ControlColumn
        {
            get
            {
                return this.controlColumnField;
            }
            set
            {
                this.controlColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ImportDefinitionColumnBasedActionType ControlColumnDefaultAction
        {
            get
            {
                return this.controlColumnDefaultActionField;
            }
            set
            {
                this.controlColumnDefaultActionField = value;
                this.controlColumnDefaultActionFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ControlColumnDefaultActionSpecified
        {
            get
            {
                return this.controlColumnDefaultActionFieldSpecified;
            }
            set
            {
                this.controlColumnDefaultActionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ControlColumnAction", IsNullable=false)]
        public ImportDefinitionColumnBasedAction[] ControlColumnActions
        {
            get
            {
                return this.controlColumnActionsField;
            }
            set
            {
                this.controlColumnActionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string EndOfLineRepresentation
        {
            get
            {
                return this.endOfLineRepresentationField;
            }
            set
            {
                this.endOfLineRepresentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string NullRepresentation
        {
            get
            {
                return this.nullRepresentationField;
            }
            set
            {
                this.nullRepresentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool StandardQuotedStrings
        {
            get
            {
                return this.standardQuotedStringsField;
            }
            set
            {
                this.standardQuotedStringsField = value;
                this.standardQuotedStringsFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StandardQuotedStringsSpecified
        {
            get
            {
                return this.standardQuotedStringsFieldSpecified;
            }
            set
            {
                this.standardQuotedStringsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public Locale DateFormattingLocale
        {
            get
            {
                return this.dateFormattingLocaleField;
            }
            set
            {
                this.dateFormattingLocaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public bool DeleteFile
        {
            get
            {
                return this.deleteFileField;
            }
            set
            {
                this.deleteFileField = value;
                this.deleteFileFieldSpecified = (value != null);
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteFileSpecified
        {
            get
            {
                return this.deleteFileFieldSpecified;
            }
            set
            {
                this.deleteFileFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public APIObject SourceObject
        {
            get
            {
                return this.sourceObjectField;
            }
            set
            {
                this.sourceObjectField = value;
            }
        }
    }
}