namespace FuelSDK
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exacttarget.com/wsdl/partnerAPI", ConfigurationName="FuelSDK.Soap")]
    public interface Soap
    {
        
        // CODEGEN: Generating message contract since the wrapper name (CreateRequest) of message CreateRequest does not match the default value (Create)
        [System.ServiceModel.OperationContractAttribute(Action="Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.CreateResponse Create(FuelSDK.CreateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RetrieveRequestMsg) of message RetrieveRequest does not match the default value (Retrieve)
        [System.ServiceModel.OperationContractAttribute(Action="Retrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.RetrieveResponse Retrieve(FuelSDK.RetrieveRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateRequest) of message UpdateRequest does not match the default value (Update)
        [System.ServiceModel.OperationContractAttribute(Action="Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.UpdateResponse Update(FuelSDK.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeleteRequest) of message DeleteRequest does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.DeleteResponse Delete(FuelSDK.DeleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (QueryRequestMsg) of message QueryRequest does not match the default value (Query)
        [System.ServiceModel.OperationContractAttribute(Action="Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.QueryResponse Query(FuelSDK.QueryRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (DefinitionRequestMsg) of message DescribeRequest does not match the default value (Describe)
        [System.ServiceModel.OperationContractAttribute(Action="Describe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.DescribeResponse Describe(FuelSDK.DescribeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ExecuteRequestMsg) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.ExecuteResponse1 Execute(FuelSDK.ExecuteRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (PerformRequestMsg) of message PerformRequest does not match the default value (Perform)
        [System.ServiceModel.OperationContractAttribute(Action="Perform", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.PerformResponse Perform(FuelSDK.PerformRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConfigureRequestMsg) of message ConfigureRequest does not match the default value (Configure)
        [System.ServiceModel.OperationContractAttribute(Action="Configure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.ConfigureResponse Configure(FuelSDK.ConfigureRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ScheduleRequestMsg) of message ScheduleRequest does not match the default value (Schedule)
        [System.ServiceModel.OperationContractAttribute(Action="Schedule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.ScheduleResponse Schedule(FuelSDK.ScheduleRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (VersionInfoRequestMsg) of message VersionInfoRequest does not match the default value (VersionInfo)
        [System.ServiceModel.OperationContractAttribute(Action="VersionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.VersionInfoResponse1 VersionInfo(FuelSDK.VersionInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ExtractRequestMsg) of message ExtractRequest does not match the default value (Extract)
        [System.ServiceModel.OperationContractAttribute(Action="Extract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.ExtractResponse Extract(FuelSDK.ExtractRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (SystemStatusRequestMsg) of message GetSystemStatusRequest does not match the default value (GetSystemStatus)
        [System.ServiceModel.OperationContractAttribute(Action="GetSystemStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParameterDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveOption[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermissionSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Permission[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PicklistItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrackingUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FieldMap[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTaskInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationTask[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessUnit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SsoIdentity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subscriber[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AutomationInstance[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValidationResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request[]))]
        FuelSDK.GetSystemStatusResponse GetSystemStatus(FuelSDK.GetSystemStatusRequest request);
    }
}